# 本文件为配置文件 *为必填项
folder: 'resource/'     # *资源所在文件夹路径
keep_temp: False  # *是否保留临时文件
save_path: 'result/'          # *保存路径
AlbumCover:
  albumen: ''          # 专辑名称
  title: ''               # 歌曲名称
  artist: ''             # 歌手名称 以上三项任意一项手动则全部手动
  albumcover: ''         # *专辑封面路径
  cn_font: C:\Windows\Fonts\*.ttc # 中文字体路径
  en_font: C:\Windows\Fonts\*.ttc # 英文字体路径
  jp_font: C:\Windows\Fonts\*.ttc # 日文字体路径
  ot_font: C:\Windows\Fonts\*.ttf # 其他文字体路径 手动指定
  choose_font: 'jp' # *选择字体
  FONT_SIZE_LARGE: 115 # *大字体大小
  FONT_SIZE_SMALL: 60 # *小字体大小
Lrc2Srt:
  cn_font: 'Consolas' # *中文字体名称
  en_font: 'Consolas' # *英文字体名称
  jp_font: 'Consolas' # *日文字体名称
  ot_font: 'Consolas' # *其他文字体名称 手动指定
  main_font: 'jp' # *双语模式下选择原文字体
  sub_font: 'cn' # *选择译文字体
ffmpeg:               # *ffmpeg配置
  path: ffmpeg # *ffmpeg路径 如果环境已配置可只填ffmpeg
  frame: 2440x1080      # *分辨率
  fps: 30               # *帧率
  crf: 18               # *视频质量, 越小质量越高, 一般在18-28之间
  vcodec: h264_nvenc      # *视频编码器, libx264为h264编码, libx265为h265编码 libaom-av1 libvpx h264_nvenc
  -b:v: 10000k           # *视频码率, 一般为900k
  -preset: slow     # *编码速度, 越慢表示压缩率越高，文件越小，但编码时间也越长。medium
  -pix_fmt: yuv420p     # *视频像素格式, 一般为yuv420p
  final_video_name: '' # 最终视频文件名


